version: '3.8'

services:

  redis:
    image: redis:7.2.5
    restart: always
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  mysql:
    image: mysql:8.0.37
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql

  sidekiq:
    build: .
    command: sh -c "bundle exec sidekiq"
    restart: always
    volumes:
      - .:/app
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  
  api:
    build: .
    command: sh -c "sh ./init.sh"
    restart: always
    volumes:
      - .:/app
    ports:
      - "4000:3000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      REDIS_HOST: redis
      REDIS_PORT: 6379

volumes:
  mysql-data:
  redis-data: