@port = 4000
# apps
### Get all apps
GET http://localhost:{{port}}/api/v1/apps

### Create an app
POST http://localhost:{{port}}/api/v1/apps
Content-Type: application/json

{
    "name": "Mac Pro"
}

### Get app by token
GET http://localhost:{{port}}/api/v1/apps/487288005

### Update app by token
PATCH http://localhost:{{port}}/api/v1/apps/487288005
Content-Type: application/json

{
    "name": "Updated xx"
}

#################################################

# chats

### Get all chats for an application
GET http://localhost:{{port}}/api/v1/apps/88349803/chats

### Get a specific chat for an application
GET http://localhost:{{port}}/api/v1/apps/9654102836/chats/1

### Create a chat for an application
POST http://localhost:{{port}}/api/v1/apps/9654102836/chats
Content-Type: application/json

#################################################

# messages

### Get all messages for a chat
GET http://localhost:{{port}}/api/v1/apps/9654102836/chats/1/messages

### Get a specific message for a chat
GET http://localhost:{{port}}/api/v1/apps/839104685/chats/63/messages/1000

### Create a message for a chat
POST http://localhost:{{port}}/api/v1/apps/9654102836/chats/1/messages
Content-Type: application/json

{
    "message": {
        "content": "Hello, worldsss!"
    }
}
### search for message (using elastic search)
GET http://localhost:{{port}}/api/v1/apps/9654102836/chats/1/messages/search/elastic?page=1&per_page=10&query=world hello
