@port = 4000
# apps
### Get all apps
GET http://localhost:{{port}}/api/v1/apps

### Create an app
POST http://localhost:{{port}}/api/v1/apps
Content-Type: application/json

{
    "name": "Mac Pro"
}

### Get app by token
GET http://localhost:{{port}}/api/v1/apps/487288005

### Update app by token
PATCH http://localhost:{{port}}/api/v1/apps/487288005
Content-Type: application/json

{
    "name": "Updated xx"
}

#################################################
# chats

### Get all chats for an application
GET http://localhost:{{port}}/api/v1/apps/88349803/chats

### Get a specific chat for an application
GET http://localhost:{{port}}/api/v1/apps/487288005/chats/1

### Create a chat for an application
POST http://localhost:{{port}}/api/v1/apps/88349803/chats
Content-Type: application/json

#################################################
# messages

### Get all messages for a chat
GET http://localhost:{{port}}/api/v1/apps/88349803/chats/1/messages

### Get a specific message for a chat
GET http://localhost:{{port}}/api/v1/apps/839104685/chats/63/messages/1000

### Create a message for a chat
POST http://localhost:{{port}}/api/v1/apps/88349803/chats/1/messages
Content-Type: application/json

{
    "message": {
        "content": "Hello, world!"
    }
}

### Update a message for a chat TODO: 
# PATCH http://localhost:{{port}}/api/v1/apps/213776/chats/1/messages/42
# Content-Type: application/json

# {
#     "message": {
#         "content": "Updated message content"
#     }
# }

### Search messages for a chat TODO:
# GET http://localhost:{{port}}/api/v1/apps/213776/chats/1/messages/search?query=Hello



# #NOTES:
# # testing from terminal: 
# # create chat
# # Replace 1000 with the number of iterations you need
# for (( i=1; i<=1000; i++ )); do
#   curl -X POST -H "Content-Type: application/json" -d '{"your_data": "here"}' http://localhost:3000/api/v1/apps/88349803/chats &
# done


# #create message
# # Replace 1000 with the number of iterations you need
# for (( i=1; i<=1000; i++ )); do   curl -X POST -H "Content-Type: application/json" -d '{"message": {"content": "Hello, world!"}}' http://localhost:4000/api/v1/apps/88349803/chats/1/messages & done